# Labeler configuration for automatic PR labeling
# See https://github.com/actions/labeler for syntax

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md']

# GitHub workflows and actions
github-actions:
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**']

# Python code changes
python:
  - changed-files:
    - any-glob-to-any-file: ['**/*.py']

# Test changes
tests:
  - changed-files:
    - any-glob-to-any-file: ['**/tests/**', '**/*test*.py']

# API changes
api:
  - changed-files:
    - any-glob-to-any-file: ['**/api/**']

# Machine Learning module changes
ml-module:
  - changed-files:
    - any-glob-to-any-file: ['**/MachineLearningModule/**']

# Feature Extraction module changes
feature-extraction:
  - changed-files:
    - any-glob-to-any-file: ['**/FeatureExtractionModule/**']

# Configuration files (excluding GitHub workflows)
config:
  - changed-files:
    - any-glob-to-any-file: ['**/*.json', '.gitignore', '.gitattributes', '**/config/**']
